name: Build & Deploy Go App

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

env:
  GO_VERSION: "1.24.3"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_PATH: ${{ vars.APP_PATH }}
      APP_PORT: ${{ vars.APP_PORT }}
      APP_NAME: ${{ vars.APP_NAME }}

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4

    - name: 🔧 Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: 🛠️ Build Go Binary
      run: |
        mkdir -p bin
        go build -ldflags="-w -s" -o bin/${APP_NAME}
        chmod +x bin/${APP_NAME}

    - name: 📄 Generate .env
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_APP_NAME: ${{ env.APP_NAME }}
        envkey_APP_PORT: ${{ env.APP_PORT }}
        envkey_ENVIRONMENT: ${{ inputs.environment }}
        file_name: .env

    - name: 📄 Generate .secrets
      run: |
        cat << EOF > .secrets
        export AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}'
        export AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        export AWS_REGION='us-east-1'
        export DYNAMODB_ENDPOINT='http://localhost:4565'
        EOF

    - name: 🔐 SSH Setup
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 🚚 Deploy to Server (scp)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        source: ".env,.secrets,bin/${{ env.APP_NAME }}"
        target: "${{ env.APP_PATH }}"

    - name: 🚀 Run App via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.APP_PATH }}
          source .secrets
          nohup ./${{ env.APP_NAME }} > /dev/null 2>&1 &