name: Build & Deploy App

on:
  push:
    branches:
      - main

env:
  APP_NAME: main
  APP_PATH: /var/www/dev/go-updater

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout source code
      uses: actions/checkout@v3

    - name: 🛠️ Build app (Go)
      run: |
        go build -o $APP_NAME main.go

    - name: 📤 Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: ".env,.secrets,main,app.sh"
        target: "${{ env.APP_PATH }}"

    - name: 🚀 Restart app on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.APP_PATH }}
          chmod +x app.sh
          ./app.sh restart